version: '3'
services:

  web:
    build: .
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - db
#      - redis
    env_file:
      - .env
    networks:
      - web_net

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - web_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
      - ./media:/app/media:ro
    depends_on:
      - web
    networks:
      - web_net

  #  celery:
  #    build: .
  #    command: celery -A myproject worker -l info
  #    volumes:
  #      - .:/app
  #    depends_on:
  #      - db
  #      - redis
  #    env_file:
  #      - .env
  #    networks:
  #      - web_net
  #  redis:
  #    image: redis:alpine
  #    networks:
  #      - web_net
networks:
  web_net:
volumes:
  db_data: